name: CI/CD Pipeline
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      run: docker build -t simple-devops-app .
    - name: Run Docker Container
      run: docker run -d -p 3000:3000 simple-devops-app
